POST http://kahoona-ion:9070/somfy/any/ping
###

POST http://kahoona-ion:9070/somfy/o3/up
###

POST http://kahoona-ion:9070/somfy/o3/down
###

POST http://kahoona-ion:9070/somfy/o3/my
###

POST http://kahoona-ion:9070/somfy/o6/prog
###

POST http://kahoona-ion:9070/somfy/o6/up
###

POST http://kahoona-ion:9070/somfy/o6/down
###

POST http://kahoona-ion:9070/somfy/o6/my
###