### List
GET http://kahoona-ion:9070/somfy/

### Get Device
GET http://kahoona-ion:9070/somfy/u1

### Ping
POST http://kahoona-ion:9070/somfy/any/ping
###

POST http://kahoona-ion:9070/somfy/o4/up
###

POST http://kahoona-ion:9070/somfy/o4/down
###

POST http://kahoona-ion:9070/somfy/o4/my
###

POST http://kahoona-ion:9070/somfy/o4/prog
###
