name: Go

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build linux amd64
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -mod=vendor -v -o somfy-rts-gateway

      - name: Test
        run: go test -mod=vendor -v ./...

      - name: Prepare arm output directory
        run: mkdir -p arm

      - name: Build linux arm
        run: GOOS=linux GOARCH=arm GOARM=5 CGO_ENABLED=0 go build -mod=vendor -v -o ./arm/somfy-rts-gateway

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gobin
          path: |
            somfy-rts-gateway
            ./arm/somfy-rts-gateway

  push_to_registry:
    name: Push Docker image to Docker Hub
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: gobin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kahoona/somfy-rts-gateway:latest

  release:
    name: Release somfy-rts-gateway
    if: github.event_name == 'push' && contains(github.ref, '/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: gobin

      - name: Zip linux amd64
        run: zip somfy-rts-gateway-linux-amd64.zip web/tmpl/* web/static/* README.md start.sh somfy.service somfy-rts-gateway

      - name: Zip linux arm
        run: zip somfy-rts-gateway-linux-arm.zip web/tmpl/* web/static/* README.md start.sh somfy.service ./arm/somfy-rts-gateway

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./README.md
          files: |
            ./somfy-rts-gateway-linux-amd64.zip
            ./somfy-rts-gateway-linux-arm.zip
